version: '3'
services:
  ##############################################################################
  #### PHP
  ##############################################################################
  php:
    build:
      context: ./src
    volumes:
        - ./src/:/src
    env_file:
        - .env
  ##############################################################################
  #### NGINX
  ##############################################################################
  nginx:
    image: nginx:1.11-alpine
    ports:
      - "8090:80"
    volumes:
      - ./env/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
    env_file:
        - .env